config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointment_question_options
  resources :appointment_question_responses
  resources :appointment_questions
  resources :appointment_titles
  resources :appointment_groups
  resources :patients
  resources :users
  resources :customers

  root 'appointment_question_responses#index'
end

app/models/appointment_group.rb
# frozen_string_literal: true

class AppointmentGroup < ApplicationRecord
  has_many :appointment_titles, dependent: :destroy
end

app/controllers/appointment_groups_controller.rb
# frozen_string_literal: true

class AppointmentGroupsController < ApplicationController
  before_action :set_appointment_group, only: %i[show edit update destroy]

  # GET /appointment_groups or /appointment_groups.json
  def index
    @appointment_groups = AppointmentGroup.all
  end

  # GET /appointment_groups/1 or /appointment_groups/1.json
  def show; end

  # GET /appointment_groups/new
  def new
    @appointment_group = AppointmentGroup.new
  end

  # GET /appointment_groups/1/edit
  def edit; end

  # POST /appointment_groups or /appointment_groups.json
  def create
    @appointment_group = AppointmentGroup.new(appointment_group_params)

    respond_to do |format|
      if @appointment_group.save
        format.html do
          redirect_to appointment_group_url(@appointment_group), notice: 'Appointment group was successfully created.'
        end
        format.json { render :show, status: :created, location: @appointment_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_groups/1 or /appointment_groups/1.json
  def update
    respond_to do |format|
      if @appointment_group.update(appointment_group_params)
        format.html do
          redirect_to appointment_group_url(@appointment_group), notice: 'Appointment group was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @appointment_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_groups/1 or /appointment_groups/1.json
  def destroy
    @appointment_group.destroy

    respond_to do |format|
      format.html { redirect_to appointment_groups_url, notice: 'Appointment group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment_group
    @appointment_group = AppointmentGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_group_params
    params.require(:appointment_group).permit(:name)
  end
end

app/helpers/appointment_groups_helper.rb
# frozen_string_literal: true

module AppointmentGroupsHelper
end

app/views/appointment_groups/_appointment_group.html.erb
<div id="<%= dom_id appointment_group %>">
  <p>
    <strong>Name:</strong>
    <%= appointment_group.name %>
  </p>

</div>

app/views/appointment_groups/_form.html.erb
<%= form_with(model: appointment_group) do |form| %>
  <% if appointment_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment_group.errors.count, "error") %> prohibited this appointment_group from being saved:</h2>

      <ul>
        <% appointment_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointment_groups/edit.html.erb
<h1>Editing appointment group</h1>

<%= render "form", appointment_group: @appointment_group %>

<br>

<div>
  <%= link_to "Show this appointment group", @appointment_group %> |
  <%= link_to "Back to appointment groups", appointment_groups_path %>
</div>

app/views/appointment_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointment groups</h1>

<div id="appointment_groups">
  <% @appointment_groups.each do |appointment_group| %>
    <%= render appointment_group %>
    <p>
      <%= link_to "Show this appointment group", appointment_group %>
    </p>
  <% end %>
</div>

<%= link_to "New appointment group", new_appointment_group_path %>

app/views/appointment_groups/new.html.erb
<h1>New appointment group</h1>

<%= render "form", appointment_group: @appointment_group %>

<br>

<div>
  <%= link_to "Back to appointment groups", appointment_groups_path %>
</div>

app/views/appointment_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment_group %>

<div>
  <%= link_to "Edit this appointment group", edit_appointment_group_path(@appointment_group) %> |
  <%= link_to "Back to appointment groups", appointment_groups_path %>

  <%= button_to "Destroy this appointment group", @appointment_group, method: :delete %>
</div>