config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointment_question_options
  resources :appointment_question_responses
  resources :appointment_questions
  resources :appointment_titles
  resources :appointment_groups
  resources :patients
  resources :users
  resources :customers

  root 'appointment_question_responses#index'
end

app/models/appointment_question.rb
# frozen_string_literal: true

class AppointmentQuestion < ApplicationRecord
  belongs_to :appointment_title
  has_many :appointment_question_options, dependent: :destroy
end

app/controllers/appointment_questions_controller.rb
# frozen_string_literal: true

class AppointmentQuestionsController < ApplicationController
  before_action :set_appointment_question, only: %i[show edit update destroy]

  # GET /appointment_questions or /appointment_questions.json
  def index
    @appointment_questions = AppointmentQuestion.all
  end

  # GET /appointment_questions/1 or /appointment_questions/1.json
  def show; end

  # GET /appointment_questions/new
  def new
    @appointment_question = AppointmentQuestion.new
  end

  # GET /appointment_questions/1/edit
  def edit; end

  # POST /appointment_questions or /appointment_questions.json
  def create
    @appointment_question = AppointmentQuestion.new(appointment_question_params)

    respond_to do |format|
      if @appointment_question.save
        format.html do
          redirect_to appointment_question_url(@appointment_question),
                      notice: 'Appointment question was successfully created.'
        end
        format.json { render :show, status: :created, location: @appointment_question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_questions/1 or /appointment_questions/1.json
  def update
    respond_to do |format|
      if @appointment_question.update(appointment_question_params)
        format.html do
          redirect_to appointment_question_url(@appointment_question),
                      notice: 'Appointment question was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @appointment_question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_questions/1 or /appointment_questions/1.json
  def destroy
    @appointment_question.destroy

    respond_to do |format|
      format.html { redirect_to appointment_questions_url, notice: 'Appointment question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment_question
    @appointment_question = AppointmentQuestion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_question_params
    params.require(:appointment_question).permit(:eye_side, :appointment_title_id)
  end
end

app/helpers/appointment_questions_helper.rb
# frozen_string_literal: true

module AppointmentQuestionsHelper
end

app/views/appointment_questions/_appointment_question.html.erb
<div id="<%= dom_id appointment_question %>">
  <p>
    <strong>Eye side:</strong>
    <%= appointment_question.eye_side %>
  </p>

  <p>
    <strong>Appointment title:</strong>
    <%= appointment_question.appointment_title_id %>
  </p>

</div>

app/views/appointment_questions/_form.html.erb
<%= form_with(model: appointment_question) do |form| %>
  <% if appointment_question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment_question.errors.count, "error") %> prohibited this appointment_question from being saved:</h2>

      <ul>
        <% appointment_question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :eye_side, style: "display: block" %>
    <%= form.text_field :eye_side %>
  </div>

  <div>
    <%= form.label :appointment_title_id, style: "display: block" %>
    <%= form.text_field :appointment_title_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointment_questions/edit.html.erb
<h1>Editing appointment question</h1>

<%= render "form", appointment_question: @appointment_question %>

<br>

<div>
  <%= link_to "Show this appointment question", @appointment_question %> |
  <%= link_to "Back to appointment questions", appointment_questions_path %>
</div>

app/views/appointment_questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointment questions</h1>

<div id="appointment_questions">
  <% @appointment_questions.each do |appointment_question| %>
    <%= render appointment_question %>
    <p>
      <%= link_to "Show this appointment question", appointment_question %>
    </p>
  <% end %>
</div>

<%= link_to "New appointment question", new_appointment_question_path %>

app/views/appointment_questions/new.html.erb
<h1>New appointment question</h1>

<%= render "form", appointment_question: @appointment_question %>

<br>

<div>
  <%= link_to "Back to appointment questions", appointment_questions_path %>
</div>

app/views/appointment_questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment_question %>

<div>
  <%= link_to "Edit this appointment question", edit_appointment_question_path(@appointment_question) %> |
  <%= link_to "Back to appointment questions", appointment_questions_path %>

  <%= button_to "Destroy this appointment question", @appointment_question, method: :delete %>
</div>