config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :appointment_question_options
  resources :appointment_question_responses
  resources :appointment_questions
  resources :appointment_titles
  resources :appointment_groups
  resources :patients
  resources :users
  resources :customers

  root 'appointment_question_responses#index'
end

app/models/appointment_title.rb
# frozen_string_literal: true

class AppointmentTitle < ApplicationRecord
  belongs_to :appointment_group
  has_many :appointment_questions, dependent: :destroy
end

app/controllers/appointment_titles_controller.rb
# frozen_string_literal: true

class AppointmentTitlesController < ApplicationController
  before_action :set_appointment_title, only: %i[show edit update destroy]

  # GET /appointment_titles or /appointment_titles.json
  def index
    @appointment_titles = AppointmentTitle.all
  end

  # GET /appointment_titles/1 or /appointment_titles/1.json
  def show; end

  # GET /appointment_titles/new
  def new
    @appointment_title = AppointmentTitle.new
  end

  # GET /appointment_titles/1/edit
  def edit; end

  # POST /appointment_titles or /appointment_titles.json
  def create
    @appointment_title = AppointmentTitle.new(appointment_title_params)

    respond_to do |format|
      if @appointment_title.save
        format.html do
          redirect_to appointment_title_url(@appointment_title), notice: 'Appointment title was successfully created.'
        end
        format.json { render :show, status: :created, location: @appointment_title }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_titles/1 or /appointment_titles/1.json
  def update
    respond_to do |format|
      if @appointment_title.update(appointment_title_params)
        format.html do
          redirect_to appointment_title_url(@appointment_title), notice: 'Appointment title was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @appointment_title }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment_title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_titles/1 or /appointment_titles/1.json
  def destroy
    @appointment_title.destroy

    respond_to do |format|
      format.html { redirect_to appointment_titles_url, notice: 'Appointment title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment_title
    @appointment_title = AppointmentTitle.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_title_params
    params.require(:appointment_title).permit(:name, :appointment_group_id)
  end
end

app/helpers/appointment_titles_helper.rb
# frozen_string_literal: true

module AppointmentTitlesHelper
end

app/views/appointment_titles/_appointment_title.html.erb
<div id="<%= dom_id appointment_title %>">
  <p>
    <strong>Name:</strong>
    <%= appointment_title.name %>
  </p>

  <p>
    <strong>Appointment group:</strong>
    <%= appointment_title.appointment_group_id %>
  </p>

</div>

app/views/appointment_titles/_form.html.erb
<%= form_with(model: appointment_title) do |form| %>
  <% if appointment_title.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(appointment_title.errors.count, "error") %> prohibited this appointment_title from being saved:</h2>

      <ul>
        <% appointment_title.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :appointment_group_id, style: "display: block" %>
    <%= form.text_field :appointment_group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointment_titles/edit.html.erb
<h1>Editing appointment title</h1>

<%= render "form", appointment_title: @appointment_title %>

<br>

<div>
  <%= link_to "Show this appointment title", @appointment_title %> |
  <%= link_to "Back to appointment titles", appointment_titles_path %>
</div>

app/views/appointment_titles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Appointment titles</h1>

<div id="appointment_titles">
  <% @appointment_titles.each do |appointment_title| %>
    <%= render appointment_title %>
    <p>
      <%= link_to "Show this appointment title", appointment_title %>
    </p>
  <% end %>
</div>

<%= link_to "New appointment title", new_appointment_title_path %>

app/views/appointment_titles/new.html.erb
<h1>New appointment title</h1>

<%= render "form", appointment_title: @appointment_title %>

<br>

<div>
  <%= link_to "Back to appointment titles", appointment_titles_path %>
</div>

app/views/appointment_titles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment_title %>

<div>
  <%= link_to "Edit this appointment title", edit_appointment_title_path(@appointment_title) %> |
  <%= link_to "Back to appointment titles", appointment_titles_path %>

  <%= button_to "Destroy this appointment title", @appointment_title, method: :delete %>
</div>